name: Post Report As Comment On PR
on:
  schedule:
    - cron: '*/1 * * * *'
check_run:
jobs:
  post-report-as-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Comment On PR
        env:
          PR: "1643"
          OWNER: operator-framework
          REPO: operator-lifecycle-manager
          TEST_SUITE: e2e
          TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: make comment-on-pr
