name: Post Report As Comment On PR
on:
  pull_request:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  post-report-as-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Comment On PR
        if: github.event.action == 'comment'
        env:
          PR: "1645"
          OWNER: operator-framework
          REPO: operator-lifecycle-manager
          TEST_SUITE: e2e-test-output
          TOKEN: ${{secrets.BOWEN_BOT}}
        run: make report-on-pr
